#pragma once

enum XACT_WAVEBANK_SOUNDS : unsigned int
{
    XACT_WAVEBANK_SOUNDS_TITLESCENE = 0,
    XACT_WAVEBANK_SOUNDS_SELECTSCENE = 1,
    XACT_WAVEBANK_SOUNDS_PLAYSCENE = 2,
    XACT_WAVEBANK_SOUNDS_GAMECLEARSCENE = 3,
    XACT_WAVEBANK_SOUNDS_GAMEOVERSCENE = 4,
};

#define XACT_WAVEBANK_SOUNDS_ENTRY_COUNT 5

enum XACT_WAVEBANK_SOUNDS_SE : unsigned int
{
    XACT_WAVEBANK_SOUNDS_SELECT = 0,
    XACT_WAVEBANK_SOUNDS_BALLOON_POP = 1,
    XACT_WAVEBANK_SOUNDS_BALLOONHIT = 2,
};

#define XACT_WAVEBANK_SOUNDS_ENTRY_COUNT_SE 3

